id: P009634
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18598
  title: བོད་ལུགས་གསོ་རིག་གི་སེམས་ཁམས་རིག་པ་དུས་རབས་ཁྱེའུ་གསར་བུའི་རང་མདངས།
  author: ''
  volumes:
    d354d4ebea2b4813a4133554b2410f05:
      image_group_id: I8LS18600
      title: ''
      volume_number: 1
      total_pages: 374
      base_file: v001.txt
